apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SuranSandeepa/ocr-inference-platform.git'
    targetRevision: HEAD
    path: charts/ocr-app #Helm files location
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true